### ISSUE TITLE
Icon position wrong on Android tablet

### ISSUE THREAD

**Issue by MHerweijer** [AmoebeLabs/flex-horseshoe-card#48]
Hi,

I hope your recovery is going well.

I'm using your Horseshoe card and on a browser or the companion app on IOS the postion of the icons is shown correct.
How ever on my (Android) wall tablet the icons are in the wrong position.
IOS:
![iOS](https://user-images.githubusercontent.com/63715723/155016839-53829d60-c59d-4dd3-851d-e196354a3c3e.jpeg)

Android
![Android](https://user-images.githubusercontent.com/63715723/155016878-0fd3b352-0766-45b1-912b-6d6b729634c5.jpeg)

Any ideas or suggestions how to fix this?

**Comment by MHerweijer** [comment]
I did some testing today and found the issue is visible when using HA with fully kiosk browser and/or wallpanel. When I open the dashboard in the companion app the cards are shown correctly. I want to use one of them to prevent the display turning of and for people to change to other apps. Any ideas?

Thanks!

**Comment by ametodi** [comment]
Was anyone able to find a solution for this?
Looks pretty and all on PC, but icons disposition in App

**Comment by MHerweijer** [comment]
Unfortunately not, still hoping it might be solved one day

**Comment by SzymaneKwr** [comment]
I have the same. Is there a solution already?
![2023-02-10_14h39_11](https://user-images.githubusercontent.com/77275930/218106920-51d801f5-2cc7-4b3b-99ed-577c36205203.jpg)
![IMG_20230210_143809](https://user-images.githubusercontent.com/77275930/218107108-4fe2d4be-037a-43cc-9430-0c69a1b98c82.jpg)

**Comment by ferchaud-byte** [comment]
je n'arrive pas à avoir le fond noir . Pourquoi il me manque une ligne. Merci

**Comment by lexiismadd** [comment]
I'm also having this issue.  Do we know if we will ever see a fix for this?  Perhaps another dev may be able to take over and fix?
FYI, it works OK in Firefox on mobile, just not chromium-based Web browsers

**Comment by AmoebeLabs** [comment]
@MHerweijer , which Android version and browser is this?

It seems as if the browser is not adhering to the latest standards, so if you can supply this, I can have a look!

**Comment by lexiismadd** [comment]
I have the issue on Samsung Tab S2, tab S3, and tab S7+ in webview. In chrome, it's ok, but i'm webview it's not.

**Comment by MHerweijer** [comment]
> @MHerweijer , which Android version and browser is this?
> 
> It seems as if the browser is not adhering to the latest standards, so if you can supply this, I can have a look!

I'm using the latest version of the companion app on Android. When I open the dashboard in chrome on the same tablet the icons are in the correct position.

**Comment by AmoebeLabs** [comment]
I think I found the culprit.

The WebView should use Blink/Chrome as the engine, so should give the exact same result as the Chrome browser.

However, the detection of the browser is done using the user agent string, and that one has changed in 2022 for the Android Companion App:
- Cause: https://github.com/home-assistant/android/issues/2438
- Result: https://github.com/home-assistant/android/pull/2442

I guess that the detection is now going wrong, as that algorithm predates this change, and that the Android Companion App is recognized as Safari!

The user agent string indeed does contain "Version/x.y Mobile Safari" according to Chrome in its user agent string: "_AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30_".

That part has been added with the 2022 change.

I can replicate the problem in Edge.
"Chromium" view:
![image](https://user-images.githubusercontent.com/7996307/235475611-137b35d7-521f-47c2-858a-5a220a0d0c2c.png)

"Safari 13.x" and "Android" view with different screen sizes:

Here you see the shift in position to the left, and that the size changes. This is also seen in the reported screenshots in this issue.

![image](https://user-images.githubusercontent.com/7996307/235475940-b3a3e5ee-c981-40c4-8786-6c5706e5b018.png)
![image](https://user-images.githubusercontent.com/7996307/235476140-548a1500-1a5d-4896-8135-d31d13421ca8.png)

If I'm right, the user agent string in the app also contains the string "Android", so that could aid in detecting the right browser, and thus selecting the right render path for - in this case - icons, which is different for Safari and Chrome/Others.

This means that I can test this locally using the Edge browser devtools. I have no Android hardware in the house.
